app/models.py
from app.database import database as db
from sqlalchemy.sql import func
from typing import List, Type


class CRUDMixin:
    def update(self, commit: bool = True, **kwargs):
        for attr, value in kwargs.items():
            setattr(self, attr, value)
        return commit and self.save()

    def save(self, commit: bool = True):
        db.session.add(self)
        if commit:
            db.session.commit()
        return self

    def delete(self, commit: bool = True):
        db.session.delete(self)
        if commit:
            db.session.commit()
        return self

    @staticmethod
    def save_all(objects: List[Type[db.Model]]):
        db.session.add_all(objects)
        db.session.commit()


class Torrent(CRUDMixin, db.Model):
    __tablename__ = "torrents"

    id = db.Column(db.Integer, primary_key=True)
    uid = db.Column(db.String(36), unique=True)
    name = db.Column(db.String(256))
    download_size = db.Column(db.Integer)
    files_count = db.Column(db.Integer)
    md5_hash = db.Column(db.String(32))
    magnet_link = db.Column(db.String)
    uploaded_at = db.Column(db.DateTime, server_default=func.now())
    is_removed = db.Column(db.Boolean, default=False)


class File(CRUDMixin, db.Model):
    __tablename__ = "files"

    id = db.Column(db.Integer, primary_key=True)
    torrent_id = db.Column(db.Integer, db.ForeignKey('torrents.id'))
    path = db.Column(db.String(256))
    size = db.Column(db.Integer)
    

app/main.py
from flask import Flask
from flask_migrate import Migrate
from app.database import database
from app.core.config import get_application_config, get_app_env
from app.views import upload, torrents


migrate = Migrate()


def get_application(env=get_app_env()) -> Flask:
    application = Flask(__name__)

    config = get_application_config(env)
    application.config.from_object(config)

    database.init_app(application)
    migrate.init_app(application, database)

    # database.create_all(app=application)

    application.register_blueprint(upload.blueprint)
    application.register_blueprint(torrents.blueprint)

    return application


app = get_application()

app/views/torrents.py
from flask import Blueprint, render_template, redirect, url_for, send_file, current_app, abort, request
from app.models import Torrent, File
import os


blueprint = Blueprint("torrents", __name__)


@blueprint.get("/")
@blueprint.get("/index")
def index():
    return redirect(url_for("torrents.retrieve_all_torrents"))


@blueprint.get("/torrents/")
@blueprint.get("/torrents/<int:page>")
def retrieve_all_torrents(page=1):
    pagination = Torrent.query.order_by(Torrent.id.desc()).paginate(page, 30, False)
    torrents = pagination.items
    return render_template("torrents_list.html", torrents=torrents, pagination=pagination)


@blueprint.get("/torrent/<string:uid>")
def retrieve_torrent_info(uid):
    torrent = Torrent.query.filter_by(uid=uid).first_or_404()
    files = File.query.filter_by(torrent_id=torrent.id).all()
    return render_template("torrent_info.html", torrent=torrent, files=files)


@blueprint.get("/torrent/<string:uid>/delete")
def delete_torrent(uid):
    torrent = Torrent.query.filter_by(uid=uid).first_or_404()
    torrent.delete()
    return redirect(url_for("torrent.index"))


@blueprint.get("/torrent/<string:uid>/raw")
def retrieve_torrent_file(uid):
    torrent = Torrent.query.filter_by(uid=uid).first_or_404()
    file_path = os.path.join(current_app.config["TORRENT_UPLOAD_PATH"], uid)

    if os.path.isfile(file_path):
        return send_file(file_path, download_name=torrent.name + ".torrent")

    abort(404)


@blueprint.get("/torrent/search")
def retrieve_search_form():
    return render_template("search_form.html")


@blueprint.get("/torrent/search/")
@blueprint.get("/torrent/search/<int:page>")
def search_by_torrents_name(page=1):
    search_query = request.args.get("query", None)
    print(search_query)
    if not search_query:
        abort(403)
    torrents = Torrent.query.filter(Torrent.name.like(f"%{search_query}%")).order_by(Torrent.id.desc()).all()
    return render_template("torrents_list.html", torrents=torrents)

app/views/upload.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from app.models import Torrent, File
from app.services.torrent import (
    generate_magnet,
    get_files_count,
    get_torrent_name,
    decode_metadata,
    calculate_download_size,
    get_file_list
)
from app.services.upload import verify_file_extension, save_file
import uuid
import hashlib
import os


blueprint = Blueprint("upload", __name__)


@blueprint.route("/upload", methods=["GET"])
def retrieve_upload_form():
    return render_template("upload.html")


@blueprint.route('/upload', methods=["POST"])
def upload_file():
    if "torrents" not in request.files:
        flash('No file part')
        return redirect(url_for("retrieve_upload_form"))

    upload_files = request.files.getlist("torrents")

    for file in upload_files:
        try:
            verify_file_extension(file.filename)
            file_raw = file.read()
            metadata = decode_metadata(file_raw)
        except Exception as e:
            flash(str(e))
            break

        torrent_name = get_torrent_name(metadata)
        download_size = calculate_download_size(metadata)
        files_count = get_files_count(metadata)
        uid = uuid.uuid4().hex
        md5 = hashlib.md5(file_raw).hexdigest()
        magnet_link = generate_magnet(metadata)

        torrent = Torrent(
            uid=uid,
            name=torrent_name,
            download_size=download_size,
            files_count=files_count,
            md5_hash=md5,
            magnet_link=magnet_link
        )

        torrent.save()

        files_obj = []
        for file in get_file_list(metadata):
            path = os.path.join(*file["path"])
            files_obj.append(File(
                torrent_id=torrent.id,
                path=path,
                size=file["length"]
            ))

        File.save_all(files_obj)
        save_file(torrent.uid, file_raw)

    return redirect("/")

app/templates/_footer.html
{% block footer %}
<hr>
<section class="search">
    <form action="{{ url_for('torrents.search_by_torrents_name') }}" method="get">
        <label>Search:</label>
        <input name="query" type="text">
        <input type="submit" value="Find!">
    </form>
<!--    <span>{#{ torrents|length }#} files</span>-->
</section>
{% endblock %}

app/templates/_header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Torrent dump</title>
    <style>
        nav {
            background-color: #07a00a;
            padding: 2px;
            margin: auto;
        }

        nav a {
            color: black;
            text-decoration: none;
            font-size: 13pt;
            font-family: Verdana, Geneva, sans-serif;
            padding-right: 2px;
        }

        nav a:not(.brand)::before {
            content: "|";
            padding-right: 4px;
        }

        .brand {
            font-weight: bold;
        }

        .container {
            max-width: 85%;
            min-width: 1080px;
            margin: auto;
        }

        main {
            background-color: #c2fac3;
            min-height: 586px;
        }

        .item-list {
            padding-top: 8px;
            border-collapse: separate;
            width: 100%;
        }

        .item-list td {
            padding: 0;
        }

        .id {
            width: max-content;
            text-align: right;
            font-size: 14pt;
            vertical-align: top;
            color: rgb(133, 133, 133);
        }

        .title {
            font-size: 14pt;
            /*word-wrap: break-word;*/
            white-space: normal;
            overflow: hidden;
            vertical-align: top;
            width: auto;
        }

        .spacer {
            height: 8px;
        }

        .actions {
            vertical-align: top;
            width: max-content;
            white-space: nowrap;
            text-align: right;
            padding-right: 8px;
        }

        .search {
            text-align: center;
            padding-bottom: 10px;
        }

        .search form {
            padding-bottom: 8px;
        }

        .search form input[type="submit"] {
            border-radius: 0px;
        }

        .size {
            text-align: right;
            width: max-content;
            white-space: nowrap;
            vertical-align: top;
        }

        .upload-form {
            padding-top: 24px;
        }

        .upload-form input {
            margin-bottom: 24px;
        }

        .header {
            text-align: left;
            color: #737373;
        }
    </style>
</head>
<body>
    <div class="container">
        <nav>
            <span>
                <a class="brand" href="{{ url_for('torrents.index') }}">Torrent dump</a>
                <a href="{{ url_for('torrents.index') }}">List</a>
                <a href="{{ url_for('torrents.retrieve_search_form') }}">Search</a>
                <a href="{{ url_for('upload.upload_file') }}">Upload</a>
            </span>
        </nav>

        <main>
            {% block content %}
            {% endblock %}
        </main>
    </div>
</body>
</html>

app/templates/search_form.html
{% extends 'base.html' %}


{% block content %}
{% include "_footer.html" %}
{% endblock %}

app/templates/torrent_info.html
{% extends "base.html" %}

{% block content %}
<h1>Torrent info</h1>
  <table>
    <tbody>
    <tr>
      <td>
        Name:
      </td>
      <td>{{ torrent.name }}}</td>
    </tr>

    <tr>
      <td>
        Download size:
      </td>
      <td>{{ '{0:,}'.format(torrent.download_size) }} bytes</td>
    </tr>

        <tr>
      <td>
        Files count:
      </td>
      <td>{{ files|length }}</td>
    </tr>

    <tr>
      <td>
        Files:
      </td>
      <td>
        <table>
          <tbody>
            {% for file in files %}
              <tr>
                <td>
                  {{ file.path }}
                </td>
                <td align="right">
                  {{ file.size }} bytes
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </td>
    </tr>
    </tbody>
  </table>
  <a href="{{ url_for('torrents.delete_torrent', uid=torrent.uid) }}">< Delete ></a>
  <a href="{{ url_for('torrents.retrieve_torrent_info', uid=torrent.uid) }}">< Info ></a>
  <a href="{{ url_for('torrents.retrieve_torrent_info', uid=torrent.uid) }}">< Torrent ></a>
  <a href="{{ torrent.magnet_link }}">< Magnet ></a>
{% endblock %}

app/templates/torrents_list.html
{% extends 'base.html' %}


{% block content %}
<table class="item-list">
    <thead>
        <tr>
            <th class="header"><a>id</a></th>
            <th class="header">title</th>
            <th class="header">size</th>
            <th class="header">actions</th>
        </tr>
    </thead>
    <tbody>
    {% for torrent in torrents %}
    <tr>
        <td class="id">{{ torrent.id }}.</td>
        <td class="title">{{ torrent.name }}</td>
        <td class="size">{{ '{0:,}'.format(torrent.download_size) }} bytes</td>
        <td class="actions">
            <a href="{{ torrent.magnet_link }}">[ magnet ]</a>
            <a href="{{ url_for('torrents.retrieve_torrent_file', uid=torrent.uid) }}">[ torrent ]</a>
            <a href="{{ url_for('torrents.delete_torrent', uid=torrent.uid) }}">[ delete ]</a>
            <a href="{{ url_for('torrents.retrieve_torrent_info', uid=torrent.uid) }}">[ info ]</a>
        </td>
    </tr>
    <tr class="spacer"></tr>
    {% endfor %}
    {% if pagination %}
    <tr>
        <td></td>
        <td colspan="3">
            {% if pagination.has_prev %}<a href="{{ url_for('torrents.retrieve_all_torrents', page=pagination.prev_num) }}">Less</a>{% endif %}
            {% if pagination.has_next %}<a href="{{ url_for('torrents.retrieve_all_torrents', page=pagination.next_num) }}">More</a>{% endif %}
        </td>
    </tr>
    {% endif %}
    </tbody>
</table>

{% include "_footer.html" %}
{% endblock %}

app/templates/upload.html
{% extends "base.html" %}

{% block content %}
<div class="form-container">
        <form class="upload-form" method="POST" enctype="multipart/form-data">
            <label>Files:</label>
            <input name="torrents" type="file" multiple>
            <br>
            <input type="submit" value="Upload files">
        </form>
    </div>
{% endblock %}